'use client'
import { useState } from 'react'
import Link from 'next/link'
import Image from 'next/image'
import { ArrowUpRight, Users, BedDouble, Heart } from 'lucide-react'
import { rooms, packages, StayPackage, money } from '@/lib/rooms'
export default function RoomCollection() {
const [stay,setStay] = useState<StayPackage>('overnight')
const [saved,setSaved] = useState<string[]>([])
return <><div className="room-toolbar"><div className="segmented" aria-label="Chọn gói lưu trú">{Object.entries(packages).map(([key,label]) => <button key={key} aria-pressed={stay === key} className={stay === key ? 'selected' : ''} onClick={() => setStay(key as StayPackage)}>{label}</button>)}</div><span>3 căn phòng · 3 cá tính riêng</span></div><div className="room-grid">{rooms.map((room,index) => <article className="room-card" key={room.id}><div className="room-image"><Link href={`/rooms/${room.id}`}><Image src={room.image} alt={`Ảnh minh họa không gian phòng ${room.name}`} fill sizes="(max-width: 700px) 100vw, 33vw"/></Link><span className="room-tag">{room.tag}</span><button className={`save-room ${saved.includes(room.id) ? 'saved' : ''}`} aria-label={`${saved.includes(room.id) ? 'Bỏ yêu thích' : 'Yêu thích'} phòng ${room.name}`} aria-pressed={saved.includes(room.id)} onClick={() => setSaved(saved.includes(room.id) ? saved.filter(id => id !== room.id) : [...saved,room.id])}><Heart size={17} fill={saved.includes(room.id) ? 'currentColor' : 'none'}/></button><span className="image-caption">Ảnh minh họa</span></div><div className="room-body"><div className="room-title"><h3><Link href={`/rooms/${room.id}`}>{room.name} Room</Link></h3><span>0{index+1}</span></div><p>{room.subtitle}</p><div className="room-amenities"><span><Users size={14}/>2 khách</span><span><BedDouble size={15}/>1 giường đôi</span><span>Không gian riêng</span></div><div className="room-price"><div><strong>{money(room.prices[stay])}</strong><span> / {stay === 'overnight' ? 'đêm' : stay === '3h' ? '3 giờ' : '6 giờ'}</span></div><Link aria-label={`Đặt phòng ${room.name}`} href={`/bookings?room=${room.id}&package=${stay}`}><ArrowUpRight size={21}/></Link></div></div></article>)}</div>{saved.length > 0 && <p className="saved-note" role="status">Bạn đang yêu thích: {rooms.filter(r => saved.includes(r.id)).map(r => r.name).join(', ')}. Lựa chọn được lưu trong phiên xem này.</p>}</>
}
