import Image from 'next/image'
import Link from 'next/link'
import { ArrowDown, ArrowUpRight, ArrowRight, Sparkles, KeyRound, ShieldCheck, Coffee, MessageCircle, Heart, Clock3 } from 'lucide-react'
import SearchBar from '@/components/booking/SearchBar'
import RoomCollection from '@/components/home/RoomCollection'
export default function Home() {
return <>
<script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "LodgingBusiness", name: "Lặng Home", telephone: "+84357907153", address: { "@type": "PostalAddress", streetAddress: "82 đường B18, KDC 91B", addressLocality: "Ninh Kiều", addressRegion: "Cần Thơ", addressCountry: "VN" }, priceRange: "150.000–380.000 VND" }) }} />
<section className="hero"><Image className="hero-photo" src="/images/pink-illustration.jpg" alt="Ảnh minh họa phòng ngủ ấm áp với ánh sáng tự nhiên" fill priority sizes="100vw"/><div className="hero-shade"/><div className="container hero-content"><span className="eyebrow"><span className="tiny-line"/> CHÀO BẠN, LẶNG ĐÂY</span><h1>Giữa bộn bề,<br/>tìm một chốn <em>lặng.</em></h1><p>Một căn phòng ấm. Một khoảng trời riêng.<br/>Để bạn nghỉ ngơi, kết nối và tận hưởng những điều nhỏ bé.</p><Link href="/rooms" className="button cream">Khám phá không gian <ArrowUpRight size={18}/></Link></div><div className="hero-bottom container"><span>STAY SLOW. FEEL AT HOME.</span><a href="#khong-gian">Kéo xuống để khám phá <ArrowDown size={14}/></a></div><span className="hero-photo-label">Không gian minh họa</span></section>
<div className="container search-wrap"><SearchBar/></div>
<section className="container intro-strip"><p><Heart size={18}/> Một nơi để đến. Một cảm giác để nhớ.</p><div><span><ShieldCheck size={17}/>Riêng tư & an tâm</span><span><KeyRound size={17}/>Self check-in</span><span><Clock3 size={17}/>Linh hoạt theo giờ</span></div></section>
<section id="khong-gian" className="container section rooms-section"><div className="section-heading"><div><span className="eyebrow">KHÔNG GIAN CỦA BẠN</span><h2>Mỗi căn phòng, một cảm xúc.</h2><p>Chọn một góc nhỏ phù hợp với tâm trạng hôm nay.</p></div><Link className="text-link" href="/rooms">Xem tất cả phòng <ArrowUpRight size={17}/></Link></div><RoomCollection/></section>
<section id="ve-lang" className="story-section"><div className="container story-grid"><div className="story-pictures"><div className="story-main"><Image src="/images/story-illustration.jpg" fill sizes="(max-width: 700px) 90vw, 40vw" alt="Ảnh minh họa góc nghỉ ngơi với nội thất gỗ và ánh nắng"/><span className="image-caption">Ảnh minh họa</span></div><div className="story-stamp">a little pause<br/><span>lặng</span><br/>a little peace</div></div><div className="story-copy"><span className="eyebrow">CÂU CHUYỆN CỦA LẶNG</span><h2>Không cần đi xa,<br/>chỉ cần <em>thấy bình yên.</em></h2><p>Có những ngày, điều mình cần chỉ là một nơi đủ yên để tạm gác lại mọi bộn bề. Một chiếc giường êm, ánh đèn ấm, và thời gian dành trọn cho bản thân hay người thương.</p><p>Lặng muốn là nơi nhỏ bé ấy. Không cầu kỳ, không vội vã — chỉ có sự riêng tư và cảm giác thoải mái như ở nhà.</p><div className="story-signature">Thương mến, <span>Lặng Home</span></div><a href="https://zalo.me/0357907153" className="text-link" target="_blank" rel="noreferrer">Chuyện trò với Lặng <ArrowUpRight size={17}/></a></div></div></section>
<section className="container section"><div className="center-heading"><span className="eyebrow">NHỮNG ĐIỀU NHỎ, ĐƯỢC CHĂM CHÚT</span><h2>Đến Lặng, cứ thoải mái là mình.</h2></div><div className="perks-grid">{[{icon:KeyRound,title:'Nhận phòng riêng tư',copy:'Chủ động vào phòng với khóa thông minh. Mã cửa được gửi riêng khi đơn được xác nhận.'},{icon:Coffee,title:'Không gian để thảnh thơi',copy:'Nghỉ ngơi, chuyện trò hay đơn giản là dành cho bản thân một khoảng lặng.'},{icon:Clock3,title:'Ở lại theo cách bạn muốn',copy:'Một cuộc hẹn 3 giờ, một chiều 6 giờ hay một đêm thật chậm. Bạn chọn, Lặng đón.'},{icon:MessageCircle,title:'Có Lặng ở đây',copy:'Cần tư vấn hay hỗ trợ nhận phòng? Chỉ một cuộc gọi hoặc tin nhắn đến Lặng.'}].map(({icon:Icon,title,copy}) => <div key={title}><span className="perk-icon"><Icon size={24} strokeWidth={1.35}/></span><h3>{title}</h3><p>{copy}</p></div>)}</div></section>
<section className="container faq-section"><div><span className="eyebrow">TRƯỚC KHI GHÉ NHÀ</span><h2>Bạn hỏi,<br/>Lặng trả lời.</h2><a href="tel:0357907153" className="text-link">Cần thêm hỗ trợ? Gọi Lặng <ArrowUpRight size={16}/></a></div><div className="faq-list">{[['Mình đặt phòng như thế nào?', 'Chọn phòng, ngày và gói lưu trú, điền thông tin liên hệ rồi thanh toán QR khi cổng thanh toán đã được kết nối. Bạn cũng có thể gọi trực tiếp 0357 907 153 để được hỗ trợ.'],['Lặng có cho thuê phòng theo giờ không?', 'Có nhé. Cả Pink, White và Black đều có gói 3 giờ, 6 giờ và qua đêm. Bạn có thể đổi gói ngay tại bảng giá để xem mức giá tương ứng.'],['Self check-in với khóa thông minh có khó không?', 'Chạm nhẹ để màn hình khóa sáng lên, nhập mã được gửi riêng rồi bấm #. Khi nghe tiếng “tít”, xoay tay nắm để vào phòng. Mã cửa không hiển thị trên lịch công khai.'],['Nếu muốn đổi lịch hoặc hủy phòng thì sao?', 'Bạn hãy liên hệ Lặng qua số 0357 907 153 và cung cấp mã đặt phòng. Điều kiện đổi lịch, hủy và hoàn tiền cần được xác nhận trực tiếp với home trước khi thanh toán.']].map(([question,answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
<section className="container final-cta"><div className="cta-doodle"><Sparkles size={40} strokeWidth={1}/></div><span className="eyebrow">MỘT CUỘC HẸN VỚI BÌNH YÊN</span><h2>Chừa một khoảng nhỏ cho mình nhé?</h2><p>Căn phòng ấm áp đang chờ. Còn lại, để Lặng lo.</p><Link href="/calendar" className="button">Tìm ngày ghé Lặng <ArrowRight size={17}/></Link></section>
<a className="floating-contact" href="https://zalo.me/0357907153" target="_blank" rel="noreferrer" aria-label="Nhắn tin với Lặng qua Zalo"><MessageCircle size={21}/><span>Nhắn Lặng</span></a>
</>
}
