<?php

function render_page(string $title, callable $content, array $options=[]): never
{
    $fullTitle=e($title).' | Lặng Home';$robots=($options['robots']??true)?'index,follow':'noindex,nofollow';
    ?><!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=$fullTitle?></title><meta name="description" content="Lặng Home — homestay riêng tư tại Ninh Kiều, Cần Thơ."><meta name="robots" content="<?=$robots?>"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="/apple-touch-icon.svg"><link rel="stylesheet" href="/assets/app.css?v=2"></head><body>
    <a class="skip-link" href="#main">Đi đến nội dung</a><?php render_header(); ?><main id="main"><?php $content(); ?></main><?php render_footer(); ?><div class="ui-toast-region" data-toast-region aria-live="polite" aria-atomic="false"></div><div class="ui-dialog-root" data-dialog-root></div><script>window.LANG_HOME={csrf:<?=json_encode(csrf_token())?>,today:<?=json_encode(date('Y-m-d'))?>};</script><script defer src="/assets/ui.js?v=2"></script><script defer src="/assets/app.js?v=2"></script></body></html><?php exit;
}
function logo(): void { ?><span class="brand"><svg width="37" height="44" viewBox="0 0 44 52" fill="none" aria-hidden="true"><path d="M5 46V21Q5 17 8 14L22 2L38 16Q40 18 43 18M38 23V44C28 48 16 37 19 27C22 15 31 26 24 37C17 47 7 45 12 42C18 38 30 49 38 44" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg><span class="brand-name">LẶNG<span>H O M E</span></span></span><?php }
function render_header(): void { ?><header class="site-header"><div class="container nav-inner"><a href="/" aria-label="Lặng Home — Trang chủ"><?php logo();?></a><nav class="nav-links" id="nav"><a href="/">Trang chủ</a><a href="/#ve-lang">Về Lặng</a><a href="/rooms">Phòng & giá</a><a href="/calendar">Lịch phòng</a><a href="/#lien-he">Liên hệ</a></nav><div class="nav-actions"><a class="nav-phone" href="tel:0357907153">☎ 0357 907 153</a><a class="button small" href="/bookings">Đặt phòng ↗</a><button class="menu-toggle" data-menu aria-label="Mở menu">☰</button></div></div></header><?php }
function render_footer(): void { ?><footer id="lien-he" class="site-footer"><div class="container footer-top"><div><?php logo();?><p>Một chốn riêng. Một nhịp chậm.<br>Một chút bình yên dành cho bạn.</p></div><div><span class="eyebrow">KHÁM PHÁ LẶNG</span><a href="/rooms">Phòng & bảng giá</a><a href="/calendar">Xem lịch phòng</a><a href="/bookings#tra-cuu">Tra cứu đặt phòng</a></div><div><span class="eyebrow">MÌNH KẾT NỐI NHÉ</span><a class="footer-phone" href="tel:0357907153">☎ 0357 907 153</a><p>82 đường B18, KDC 91B<br>Ninh Kiều, Cần Thơ</p><a href="https://zalo.me/0357907153" target="_blank" rel="noreferrer">Trò chuyện qua Zalo ↗</a></div></div><div class="container footer-bottom"><span>© <?=date('Y')?> Lặng Home.</span><span>Được chăm chút, từ những điều nhỏ nhất.</span></div></footer><?php }

function render_room_cards(): void { ?><div class="room-toolbar"><div class="segmented" data-package-tabs><?php foreach(packages() as $id=>$label):?><button type="button" data-package="<?=$id?>" class="<?=$id==='overnight'?'selected':''?>"><?=$label?></button><?php endforeach?></div><span>3 căn phòng · 3 cá tính riêng</span></div><div class="room-grid"><?php $i=0;foreach(rooms() as $room):$i++;?><article class="room-card"><div class="room-image"><a href="/rooms/<?=$room['id']?>"><img src="<?=$room['image']?>" alt="Ảnh minh họa phòng <?=e($room['name'])?>"></a><span class="room-tag"><?=e($room['tag'])?></span><span class="image-caption">Ảnh minh họa</span></div><div class="room-body"><div class="room-title"><h3><a href="/rooms/<?=$room['id']?>"><?=e($room['name'])?> Room</a></h3><span>0<?=$i?></span></div><p><?=e($room['subtitle'])?></p><div class="room-amenities"><span>♙ 2 khách</span><span>▱ 1 giường đôi</span><span>Không gian riêng</span></div><div class="room-price"><div><?php foreach($room['prices'] as $pkg=>$price):?><span class="price-option" data-price-package="<?=$pkg?>" <?=$pkg!=='overnight'?'hidden':''?>><strong><?=money($price)?></strong> / <?=e(strtolower(packages()[$pkg]))?></span><?php endforeach?></div><a href="/bookings?room=<?=$room['id']?>&package=overnight" data-book-room="<?=$room['id']?>">↗</a></div></div></article><?php endforeach?></div><?php }

function render_home(): void { ?><script type="application/ld+json"><?=json_encode(['@context'=>'https://schema.org','@type'=>'LodgingBusiness','name'=>'Lặng Home','telephone'=>'+84357907153','address'=>['@type'=>'PostalAddress','streetAddress'=>'82 đường B18, KDC 91B','addressLocality'=>'Ninh Kiều','addressRegion'=>'Cần Thơ','addressCountry'=>'VN']],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?></script>
<section class="hero"><img class="hero-photo" src="/images/pink-illustration.jpg" alt="Không gian phòng ấm áp"><div class="hero-shade"></div><div class="container hero-content"><span class="eyebrow"><span class="tiny-line"></span> CHÀO BẠN, LẶNG ĐÂY</span><h1>Giữa bộn bề,<br>tìm một chốn <em>lặng.</em></h1><p>Một căn phòng ấm. Một khoảng trời riêng.<br>Để bạn nghỉ ngơi, kết nối và tận hưởng những điều nhỏ bé.</p><a href="/rooms" class="button cream">Khám phá không gian ↗</a></div><div class="hero-bottom container"><span>STAY SLOW. FEEL AT HOME.</span><a href="#khong-gian">Kéo xuống để khám phá ↓</a></div></section>
<div class="container search-wrap"><form class="search-bar" action="/calendar"><label><span>NGÀY GHÉ LẶNG</span><input type="date" name="date" min="<?=date('Y-m-d')?>" value="<?=date('Y-m-d')?>"></label><label><span>KHÔNG GIAN</span><select name="room"><option value="all">Tất cả phòng</option><?php foreach(rooms() as $r):?><option value="<?=$r['id']?>"><?=$r['name']?> Room</option><?php endforeach?></select></label><label><span>GÓI LƯU TRÚ</span><select name="package"><?php foreach(packages() as $id=>$label):?><option value="<?=$id?>"><?=$label?></option><?php endforeach?></select></label><button class="button">Kiểm tra phòng →</button></form></div>
<section class="container intro-strip"><p>♡ Một nơi để đến. Một cảm giác để nhớ.</p><div><span>✓ Riêng tư & an tâm</span><span>⌁ Self check-in</span><span>◷ Linh hoạt theo giờ</span></div></section>
<section id="khong-gian" class="container section"><div class="section-heading"><div><span class="eyebrow">KHÔNG GIAN CỦA BẠN</span><h2>Mỗi căn phòng, một cảm xúc.</h2><p>Chọn một góc nhỏ phù hợp với tâm trạng hôm nay.</p></div><a class="text-link" href="/rooms">Xem tất cả phòng ↗</a></div><?php render_room_cards();?></section>
<section id="ve-lang" class="story-section"><div class="container story-grid"><div class="story-main"><img src="/images/story-illustration.jpg" alt="Góc nghỉ ngơi của Lặng"><span class="image-caption">Ảnh minh họa</span></div><div class="story-copy"><span class="eyebrow">CÂU CHUYỆN CỦA LẶNG</span><h2>Không cần đi xa,<br>chỉ cần <em>thấy bình yên.</em></h2><p>Có những ngày, điều mình cần chỉ là một nơi đủ yên để tạm gác lại mọi bộn bề. Một chiếc giường êm, ánh đèn ấm, và thời gian dành trọn cho bản thân hay người thương.</p><p>Lặng muốn là nơi nhỏ bé ấy. Không cầu kỳ, không vội vã — chỉ có sự riêng tư và cảm giác thoải mái như ở nhà.</p><a href="https://zalo.me/0357907153" class="text-link">Chuyện trò với Lặng ↗</a></div></div></section>
<section class="container section"><div class="center-heading"><span class="eyebrow">NHỮNG ĐIỀU NHỎ, ĐƯỢC CHĂM CHÚT</span><h2>Đến Lặng, cứ thoải mái là mình.</h2></div><div class="perks-grid"><div><span class="perk-icon">⌁</span><h3>Nhận phòng riêng tư</h3><p>Chủ động vào phòng với khóa thông minh. Mã cửa được gửi riêng khi đơn được xác nhận.</p></div><div><span class="perk-icon">☕</span><h3>Không gian thảnh thơi</h3><p>Nghỉ ngơi, chuyện trò hay đơn giản là dành cho bản thân một khoảng lặng.</p></div><div><span class="perk-icon">◷</span><h3>Ở lại theo cách bạn muốn</h3><p>Một cuộc hẹn 3 giờ, một chiều 6 giờ hay một đêm thật chậm.</p></div><div><span class="perk-icon">♡</span><h3>Có Lặng ở đây</h3><p>Cần tư vấn hay hỗ trợ nhận phòng? Chỉ một cuộc gọi hoặc tin nhắn đến Lặng.</p></div></div></section>
<section class="container final-cta"><span class="eyebrow">MỘT CUỘC HẸN VỚI BÌNH YÊN</span><h2>Chừa một khoảng nhỏ cho mình nhé?</h2><p>Căn phòng ấm áp đang chờ. Còn lại, để Lặng lo.</p><a href="/calendar" class="button">Tìm ngày ghé Lặng →</a></section><a class="floating-contact" href="https://zalo.me/0357907153">Nhắn Lặng</a><?php }

function render_rooms(): void { ?><div class="container section"><div class="center-heading"><span class="eyebrow">CHỌN MỘT GÓC NHỎ CHO RIÊNG MÌNH</span><h1>Phòng & bảng giá</h1><p>Ba sắc thái. Một cảm giác thân quen.</p></div><?php render_room_cards();?><section class="price-section"><h2>Một khoảng nghỉ, vừa với bạn.</h2><div class="table-scroll"><table><thead><tr><th>Gói lưu trú</th><?php foreach(rooms() as $r):?><th><?=$r['name']?></th><?php endforeach?></tr></thead><tbody><?php foreach(packages() as $id=>$label):?><tr><td><?=$label?></td><?php foreach(rooms() as $r):?><td><?=money($r['prices'][$id])?></td><?php endforeach?></tr><?php endforeach?></tbody></table></div><p class="muted">Giờ qua đêm, phụ thu ngày lễ và chính sách hủy cần xác nhận với home.</p></section></div><?php }
function render_room(string $id): void { $r=rooms()[$id];?><div class="container section"><a class="text-link" href="/rooms">← Tất cả phòng</a><div class="detail-grid"><div class="detail-image"><img src="<?=$r['image']?>" alt="Phòng <?=$r['name']?>"><span class="image-caption">Ảnh minh họa</span></div><div><span class="eyebrow"><?=e($r['tag'])?></span><h1><?=$r['name']?> Room</h1><p><?=e($r['description'])?></p><p class="muted">2 khách · 1 giường đôi · Self check-in</p><div class="detail-prices"><?php foreach(packages() as $pkg=>$label):?><a href="/bookings?room=<?=$id?>&package=<?=$pkg?>"><span><?=$label?></span><strong><?=money($r['prices'][$pkg])?> ↗</strong></a><?php endforeach?></div><a class="button" href="/calendar?room=<?=$id?>">Xem lịch phòng trống</a></div></div></div><?php }

function render_calendar(): void { ?><div class="container section"><div class="center-heading"><span class="eyebrow">CHỌN NGÀY GHÉ LẶNG</span><h1>Lịch phòng</h1><p>Lịch công khai không hiển thị thông tin của khách.</p></div><div id="calendar-app" class="calendar-layout"><section class="panel"><div class="calendar-nav"><button class="icon-button" data-month-prev>‹</button><h2 data-month-title></h2><button class="icon-button" data-month-next>›</button></div><div class="month-grid" data-calendar-grid></div><div class="form-grid form-section"><label class="field">Gói lưu trú<select data-cal-package><?php foreach(packages() as $id=>$label):?><option value="<?=$id?>"><?=$label?></option><?php endforeach?></select></label><label class="field">Giờ nhận phòng<input type="time" value="14:00" data-cal-time></label></div></section><section class="panel"><div class="calendar-nav"><h2 data-selected-title></h2><button class="icon-button" data-refresh>↻</button></div><label class="field">Không gian<select data-cal-room><option value="all">Tất cả phòng</option><?php foreach(rooms() as $r):?><option value="<?=$r['id']?>"><?=$r['name']?> Room</option><?php endforeach?></select></label><div data-availability></div></section></div></div><?php }

function render_bookings(): void { ?><div class="container section"><div class="center-heading"><span class="eyebrow">CHỌN MỘT CUỘC HẸN</span><h1>Đặt phòng</h1><p>Thông tin giá và tình trạng phòng luôn được kiểm tra lại trên máy chủ.</p></div><div id="booking-app" class="booking-grid"><form class="panel" data-booking-form><h2>Cuộc hẹn của bạn</h2><div class="form-grid"><label class="field">Không gian<select name="roomId"><?php foreach(rooms() as $r):?><option value="<?=$r['id']?>"><?=$r['name']?> Room</option><?php endforeach?></select></label><label class="field">Gói lưu trú<select name="stayPackage"><?php foreach(packages() as $id=>$label):?><option value="<?=$id?>"><?=$label?></option><?php endforeach?></select></label><label class="field">Ngày ghé Lặng<input name="date" type="date" min="<?=date('Y-m-d')?>" required></label><label class="field">Giờ nhận phòng<input name="time" type="time" value="14:00" required></label></div><div class="form-section"><h2>Mình làm quen nhé</h2><div class="form-grid"><label class="field">Họ và tên *<input name="guestName" minlength="2" maxlength="100" required></label><label class="field">Số điện thoại *<input name="guestPhone" type="tel" maxlength="20" required></label><label class="field">Email<input name="guestEmail" type="email" maxlength="254"></label><label class="field">Số khách<select name="numberOfGuests"><option value="1">1 người lớn</option><option value="2" selected>2 người lớn</option></select></label><label class="field full">Một lời nhắn cho Lặng<textarea name="guestNote" rows="3" maxlength="1000"></textarea></label></div></div><div class="notice" data-terms hidden></div><label class="check"><input type="checkbox" name="acceptTerms" required> Tôi đã đọc điều kiện đặt phòng và đồng ý để Lặng sử dụng thông tin liên hệ xử lý đơn này.</label><div data-booking-message></div><button class="button wide" type="submit">Tiếp tục thanh toán →</button></form><aside class="panel" data-summary></aside></div><?php render_lookup();?></div><?php }
function render_lookup(): void { ?><section class="panel lookup-panel" id="tra-cuu"><h2>Bạn đã có một cuộc hẹn?</h2><p class="muted">Tra cứu bằng mã đặt phòng và số điện thoại đã sử dụng.</p><form class="lookup-form" data-lookup-form><label class="field">Mã đặt phòng<input name="code" required placeholder="LANG-…"></label><label class="field">Số điện thoại<input name="phone" type="tel" required></label><button class="button">Tra cứu đặt phòng</button></form><div data-lookup-result></div></section><?php }
function render_payment(): void { ?><div class="container section"><div class="payment-container panel text-center" id="payment-app" data-code="<?=e($_GET['code']??'')?>"><span class="eyebrow">HOÀN TẤT CUỘC HẸN</span><h1>Thanh toán đặt phòng</h1><div data-payment-result><p class="notice">Đang tải thông tin thanh toán…</p></div></div></div><?php }
function render_login(string $error): void { ?><div class="container section"><div class="panel payment-container"><span class="eyebrow">DÀNH CHO CHỦ HOME</span><h1>Đăng nhập quản lý</h1><p class="muted">Khách đặt phòng không cần tạo tài khoản.</p><form method="post" class="stack"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><label class="field">Email<input name="email" type="email" required></label><label class="field">Mật khẩu<input name="password" type="password" required></label><?php if($error):?><p class="notice error"><?=e($error)?></p><?php endif?><button class="button">Đăng nhập</button></form></div></div><?php }
function render_admin(): void { ?><div class="container section"><div class="section-heading"><div><span class="eyebrow">KHÔNG GIAN QUẢN LÝ</span><h1>Chào chủ nhà.</h1><p>100 đơn gần nhất · giờ Việt Nam</p></div><form action="/logout" method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><button class="button outline">Đăng xuất</button></form></div><div id="admin-app"><p class="notice">Đang tải danh sách đơn…</p></div></div><?php }
